# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-15 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indexBanerSll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('backColor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'indexBanerSll',
            },
        ),
        migrations.CreateModel(
            name='indexDrb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tits', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=20)),
                ('price2', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'indexDrb',
            },
        ),
        migrations.CreateModel(
            name='indexLouti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tits', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=20)),
                ('price2', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'indexLouti',
            },
        ),
        migrations.CreateModel(
            name='indexMrb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'indexMrb',
            },
        ),
    ]
